### ISSUE TITLE
Permit For Using Source Code

### ISSUE THREAD

**Issue by diofaprogsoft** [jakesee/excel-sets#1]
Dear jakesee, 
Thank you for creating this source code. Because I'm trying to build an app that needs this source code. I am requesting permission to learn and use this source code. And later I will enter into the credit source of my application code. 
Regards, 
diofanta

**Comment by jakesee** [comment]
@diofanta hope you found some use for the code. Please feel free to use the code and credit as mentioned. Thanks.
